# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Cs2SEONo8qHs0k7oGt6pS9EFOEvhrI_
"""

def kasallik_tashxisi(belgi):
    if belgi == "isitma":
        return "Parasetamol iching"
    elif belgi == "tish og'rig'i":
        return "Qupen iching"
    elif belgi == "qorin og'rig'i":
        return "Levomitsin iching"
    elif belgi == "yo'tal":
        return "Mukaltin iching"
    elif belgi == "bosh og'rig'i":
        return "Analgin iching"
    elif belgi == "allergiya":
        return "Tavegil iching"
    elif belgi == "ich qotishi":
        return "Dufalak iching"
    elif belgi == "qonli yiring":
        return "Furacilin bilan yuvib ko'ring"
    elif belgi == "ko'z og'rig'i":
        return "Oftalmol iching"
    elif belgi == "mushak og'rig'i":
        return "Diklofenak surting"
    else:
        return "Shifokorga murojaat qiling"

belgi = input("Kasallik belgisini kiriting: ")
natija = kasallik_tashxisi(belgi)
print(natija)